services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" # web ui: http://localhost:6333/dashboard
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"
      QDRANT__SERVICE__GRPC_PORT: "6334"
      QDRANT__SERVICE__HTTP_PORT: "6333"

volumes:
  qdrant_data:
