name: Test

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  check-msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Set Rust caching env vars
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - run: rustup component add rustfmt clippy
      - name: check
        run: |
          cargo check --workspace --all-targets --all-features
      - name: clippy
        run: |
          cargo clippy --workspace --all-targets --all-features
      - name: rustfmt
        run: |
          cargo fmt --all --check
