name: Test

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  check-msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.11
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
      - run: rustup component add rustfmt clippy
      - name: check
        run: |
          cargo check --workspace --all-targets --all-features
      - name: clippy
        run: |
          cargo clippy --workspace --all-targets --all-features
      - name: rustfmt
        run: |
          cargo fmt --all --check
